<?php

namespace AppBundle\Repository;

/**
 * RecipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipesRepository extends \Doctrine\ORM\EntityRepository
{
}
